### ISSUE TITLE
PQService for Linux

### ISSUE THREAD

**Issue by ppodhajski** [uic-evl/omicron#27]
Hi,
OMICRON_USE_PQLABS seems to work only for WIN32. Is it possible to run it on Linux?  I found only some dll's in /external

**Comment by arthurnishimoto** [comment]
Hi,

As far as I'm aware PQLabs do not have SDK support for Linux (https://www.pqlabs.com/sdk.html). Even the OSX support seems a few years out of date compared to the Windows SDK support.

We typically run PQLabs and oinputserver on a Windows machine connected to the PQLabs overlay and use an Omicron client on the Linux side to get the data.

**Comment by ppodhajski** [comment]
Hi,
I see it now. Another option could be creating a TUIO service as PQLabs software supports this protocol. I may have a look into that if we decide to use it this way. Having a separate Windows machine is a bit cumbersome.

**Comment by arthurnishimoto** [comment]
Hi,
I've added Linux support for PQService (commit: 356735f9e05e61cf4aaa3be0bf759dacbaff7aec). Backend it uses TUIO, but translates the events as if they were provided by the SDK as normal. The one difference is that there is no blob size data provided in PQLabs TUIO implementation as far as I can tell - thus the touch width/height will always be fixed.

**Comment by ppodhajski** [comment]
Hi,
Thanks it works, I can see the touch events transmitted to SAGE. It needed a small fix, so I opened a PR.

I have a question, which I am not sure if should be posted here as it is related to SAGE more. The cursor is visible and windows react to the cursor being moved over them (they would change the border color when hovered on) but there is no interaction, i.e. I cannot move a window as I would do with the pointer in the webinterface. I tried using different "interactionMode" but no difference. The only thing which responded to touch events was the whiteboard palette.

Let me know if I should post it to sage google group instead.

Cheers,
Pawel

**Comment by arthurnishimoto** [comment]
Hi Pawel,

I would make sure that useGestureManager = true is set in the oinputserver.cfg under PQService. Otherwise touch support in SAGE is still experimental and currently not a high priority.

Feel free to post to the SAGE Google Group if you need further assistance. Would be good to let the community know there's still interest in touch development in SAGE.

- Arthur
